[object_store]
total_mbytes = 256
free_mbytes = 128

[root]
host_root = "D:\\INAVI_Emulator\\EmulatorRoot"

[[mounts]]
name = "sdmmc"
device_name = "DSK5:"
guest_root = "\\SDMMC Disk"
host_root = "D:\\INAVI_Emulator\\INAVI"
total_mbytes = 8192
free_mbytes = 4096
writable = true
removable = true
system = false
hidden = false
interface_classes = [
    "{A4E7EDDA-E575-4252-9D6B-4195D48BB865}",
    "{A32942B7-920C-486b-B0E6-92A702A99B35}",
    "{8DD679CE-8AB4-43c8-A14A-EA4963FAA715}",
]

[[mounts]]
name = "resident_flash"
guest_root = "\\ResidentFlash"
host_root = "D:\\INAVI_Emulator\\DUMPPLZ\\ResidentFlash"
total_mbytes = 64
free_mbytes = 38
writable = true
removable = false
system = false
hidden = false

[[mounts]]
name = "windows"
guest_root = "\\Windows"
total_mbytes = 2048
free_mbytes = 1024
writable = false
removable = false
system = true
hidden = false
