[object_store]
total_mbytes = 256
free_mbytes = 128

[[mounts]]
name = "sdmmc"
guest_root = "\\SDMMC Disk"
host_root = "D:\\INAVI_Emulator\\INAVI"
total_mbytes = 8192
free_mbytes = 4096
writable = true
removable = true
system = false
hidden = false

[[mounts]]
name = "resident_flash"
guest_root = "\\ResidentFlash"
host_root = "D:\\INAVI_Emulator\\DUMPPLZ\\ResidentFlash"
total_mbytes = 64
free_mbytes = 38
writable = false
removable = false
system = false
hidden = false

[[mounts]]
name = "windows"
guest_root = "\\Windows"
total_mbytes = 2048
free_mbytes = 1024
writable = false
removable = false
system = true
hidden = false
